#!/usr/bin/env python3

import cgi
import math
from datetime import datetime as dt

def isPrime(n: int) -> bool:
    for i in range (2, n // 2 + 1):
        if n % i == 0:
            return False
    return True

def getNPrimes(n):
    i = 2
    lst = []
    while True:
        if isPrime(i):
            lst.append(i)
        i = i + 1
        if len(lst) >= n:
            return lst


params = cgi.FieldStorage()
name = params['name'].value
n = int(params['n'].value)

print('Content-Type: text/html')
print()
print('<html')
print('  <head>')
print('    <title>Hello CS330</title>')
print('  </head>')
print('<script type="text/javascript" src="/hello.js"></script>')
print('  <body>')
print('<h1>Hello {}!</h1>'.format(name))
print('<p>Today is <em>{}</em></p>'.format(dt.now()))
print('<p>')
if isPrime(n):
    print('Python says {} is prime'.format(n))
else:
    print('Python says {} is NOT prime'.format(n))
print('</p>')
print('<p>')
print('Javascript says {} is '.format(n))
print('<script>document.write(isPrime({}) ? "prime" : "NOT prime")</script>'.format(n))
print('</p>')
print('<p>The list of the first n prime numbers: ')
print(getNPrimes(n))
print('</p>')
print('<p>First 4 prime numbers generated by JavaScript: <script>document.write("[",getNPrimes(4),"]")</script></p>')
print('  </body>')
print('</html>')
